language: cpp
dist: trusty
sudo: required

os:
- linux

compiler:
- g++

python:
- "2.7"
- "3.3"
- "3.4"
- "3.5"
- "3.6"

matrix:
  include:
    - python: 2.7
      env: PYTHON_ROOT=/opt/python/2.7
    - python: 3.3
      env: PYTHON_ROOT=/opt/python/3.3
    - python: 3.4
      env: PYTHON_ROOT=/opt/python/3.4
    - python: 3.5
      env: PYTHON_ROOT=/opt/python/3.5
    - python: 3.6
      env: PYTHON_ROOT=/opt/python/3.6

before_install:
- echo $TRAVIS_PYTHON_VERSION
- git clone --depth=1 https://github.com/nnarain/travis-ci-scripts.git ~/scripts
- cd ~/scripts/ && ./bootstrap && cd -
- preinstall_general
- install_boost 1.60.0 linux --with-system --with-python
- source /opt/boost_1_60_0/setup.bash
- sudo apt-get install python-dev -qq

install:
- export PATH=$PYTHON_ROOT/bin:$PYTHON_ROOT/lib:$PATH
- python --version
- pip --version
- pip install wheel

script:
- python setup.py build

after_success:
- python setup.py bdist_wheel

deploy:
  provider: pypi
  user: nnarain
  password:
    secure: IWA+Hir8il0zEmOzaVylb8GzgW961uel5PfGP1ezmY2eE5UtVw+XifVgWiW5+4JMWP8bPWcLu2sZtdKet2+JXjuCVFjkzCTCMJ/a9u+RwJ66KEcivoW0KLVOM8CyqqIh2c5ol7SLI6AqtpBq1C9VbWd7N7hLkf5TA+4XxybB77O/fsZrBBatFmDrbcISlq23kjdTjY+TF0p3EKzZtQ2RJ08rnLnnjWaZXg0b3AjddaY0MD51D0yiDsLgg070gttHSqYwV15ppqzbBDEtzForMlAcp32+oqo6GJZFd86PbbsyhnubIcfar4giONZE/ZngrE4gMR1NzIh9jtpP64IHM3+D13up0Pizn7p7abE8VH9xHqjIEWzw9LhGshEL4HcA5JdMQEvF0PPQoFbfanbtnaDE/d7snbByMuXVXfxB4RICXsB9S2vzMROCklYP45lL0uibVRpeqymJZowT8XBPTw9mLeLAKLC6xYvkdPmOe4gGAr/mxX6kVyrxywDXCX0Q98CbKl5Lw3E1mg0xYhRVelEO7+U2CGRwbfuKt8QdZkQl5CfYA6d0qYpwsl0Rg8RAVsvm8NZR11Xktmc4Ao8T6ZI+yc3hvU0sHmmHV48SEfdKfV3QpV7cv0NypuZ93aifZ4074Q/f2ik03LEz0gH4icp6o4W4NzUr4Bwms/tuXbc=
  distributions: "bdist_egg"
