language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
           PLAT=manylinux1_x86_64

    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
           PRE_CMD=linux32
           PLAT=manylinux1_i686

    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
           PLAT=manylinux2010_x86_64

install:
  - docker pull $DOCKER_IMAGE
  - pip install -U twine
  - mkdir wheelhouse/

script:
  - docker run --rm -e PLAT=$PLAT -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD bash /io/ci/travis/build.sh
  - ls wheelhouse/

after_success:
  - mkdir dist
  - mv wheelhouse/* dist/

deploy:
  provider: pypi
  user: nnarain
  password:
    secure: AxAqP6HNSijVIC0AOu7Jnuy6fZ3fp8C9oBsJvq2s16ezrMKpuUP96QlmIErE1nkxqfu3dt2lQ8P1jMm8r77zIZQnniLoiJlAOihm8WIVw9BskLn33PbHeLi7pA9hZigo4KUuxasdomwCDLxeBH4gFJnlN/qK6XZx4iH9mGBdDlz5PDJ4d1EFOBCBA/A3+r61l2euyHuGwYkSDqcJUlQaOKhMlufVG0vIcPf1kXBFNxVbbpHUdB5XufKh+ET4eImUQXQ5ZpuJf6+QYFXvDFm6wyV6haeOlUlT33t1ZkONTKRCsnVonX+Pj4MDntPu3aLarzCotBhwhERTxmWmr95MxBZsXE+pr0futFIZDCMWa1HwHkiTVmsAxwprihEODZ2cLIzp69RPmHsfTJfCUzgR9lvTeOuKQ5SQ5v/nz1GiGduBxf9yRHDFfacbkiAH6GxtB17QUtEl6l+AkDXy4j8Z4ylYbNVNPApcGhxSvSnJi54FgkITtsOxNPkE10SXkDKJDfUpDT5Sxf8aGEYhy8ZDl1pAV2m9sImRRcAt1GSfJrloR77qYjnrgEhrvvQ3FSKMy37HmkwLAq7evZqYDrglQ6hd2JH06vWkuJKC4lAoXrzui6c7mgM+fY1lrkjAT1lVMem0/SLjpYlHZJYBYvTwMOzqNzR/VgQQN1NZyavNoZk=
  on:
    all_branches: true
  skip_existing: true
  skip_cleanup: true
