os: Visual Studio 2015

clone_folder: c:\projects\gameboycore-python

branches:
  only:
    - master

environment:
  password:
    secure: VQENOcOB+fwiDwZ+Ojntvw==

  matrix:
    - PYTHON_ROOT: "C:\\Python34"
      PYTHON_VERSION: 3.4
      ARCH: 32
    - PYTHON_ROOT: "C:\\Python34-x64"
      PYTHON_VERSION: 3.4
      ARCH: 64
    - PYTHON_ROOT: "C:\\Python35"
      PYTHON_VERSION: 3.5
      ARCH: 32
    - PYTHON_ROOT: "C:\\Python35-x64"
      PYTHON_VERSION: 3.5
      ARCH: 64
    - PYTHON_ROOT: "C:\\Python36"
      PYTHON_VERSION: 3.6
      ARCH: 32
    - PYTHON_ROOT: "C:\\Python36-x64"
      PYTHON_VERSION: 3.6
      ARCH: 64
    - PYTHON_ROOT: "C:\\Python37"
      PYTHON_VERSION: 3.7
      ARCH: 32
    - PYTHON_ROOT: "C:\\Python37-x64"
      PYTHON_VERSION: 3.7
      ARCH: 64

init:
  - set PATH=%PYTHON_ROOT%;%PYTHON_ROOT%\Scripts;%PYTHON_ROOT%\Lib;%PATH%

install:
  - python --version
  - pip --version
  - pip install setuptools --upgrade
  - pip install wheel
  - pip install nose

build_script:
  - cd c:\projects\gameboycore-python
  - git submodule init && git submodule update
  - pip install -e .
  - nosetests -v -w tests

deploy_script:
  - set HOME=%USERPROFILE%
  - echo [pypirc] > %HOME%\\.pypirc
  - echo servers=pypi >> %HOME%\\.pypirc
  - echo [server-login] >> %HOME%\\.pypirc
  - echo username:nnarain >> %HOME%\\.pypirc
  - "echo password:%password% >> %HOME%\\.pypirc"
  - python setup.py bdist_wheel upload
