os: Visual Studio 2015

clone_folder: c:\projects\gameboycore-python

environment:
  matrix:
    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5.2"
      PYTHON_ARCH: "32"

  BOOST_ROOT: C:\Libraries\boost_1_60_0

  password:
    secure: bkWnSpT47YhbxGA3RUIBTcvQOPbPG5ziYsQtLOE1L/c=

init:
  - set PYTHON_ROOT=%PYTHON%
  - set PATH=%PYTHON%;%PATH%

install:
  - python --version
  - pip --version
  - pip install setuptools --upgrade
  - pip install wheel

build_script:
  - cd c:\projects\gameboycore-python
  - git submodule init
  - git submodule update
  - python setup.py build

deploy_script:
  - "echo [pypi] > %USERPROFILE%\\.pypirc"
  - "echo username: nnarain >> %USERPROFILE%\\.pypirc"
  - "echo password: %password% >> %USERPROFILE%\\.pypirc"
  - python setup.py sdist bdist_wheel upload
