os: Visual Studio 2015

clone_folder: c:\projects\gameboycore-python

environment:
  PYTHON_ROOT: "C:\\Python35"

  BOOST_ROOT: C:\Libraries\boost_1_60_0
  BOOST_LIB_DIR: lib32-msvc-14.0

  password:
    secure: bkWnSpT47YhbxGA3RUIBTcvQOPbPG5ziYsQtLOE1L/c=


install:
  - pip install setuptools --upgrade
  - pip install scons
  - git clone --depth=1 https://github.com/boostorg/python.git c:\libs\boost_python
  - c:\libs\boost_python
  - scons --boost=%BOOST_ROOT% --python=%PYTHON_ROOT%
  - set PATH=%PYTHON_ROOT%;%PYTHON_ROOT%\Scripts;%PYTHON_ROOT%\Lib;%PATH%
  - python --version
  - pip --version
  - pip install setuptools --upgrade
  - pip install wheel
  - dir C:\Libraries\boost_1_60_0\tools\build

before_build:
  - cd c:\projects\gameboycore-python
  - cp config/appveyor/user-config.jam C:\Libraries\boost_1_60_0
  - cd C:\Libraries\boost_1_60_0
  - bjam --with-python python-debugging=off threading=multi variant=release link=statick=static

build_script:
  - cd c:\projects\gameboycore-python
  - git submodule init
  - git submodule update
  - python setup.py build

deploy_script:
  - "echo [pypi] > %USERPROFILE%\\.pypirc"
  - "echo username: nnarain >> %USERPROFILE%\\.pypirc"
  - "echo password: %password% >> %USERPROFILE%\\.pypirc"
  - python setup.py sdist bdist_wheel upload
