os: Visual Studio 2015

clone_folder: c:\projects\gameboycore-python

environment:
  PYTHON_ROOT: "C:\\Python35"

  BOOST_ROOT: C:\Libraries\boost_1_60_0
  BOOST_LIB_DIR: lib32-msvc-14.0

  password:
    secure: bkWnSpT47YhbxGA3RUIBTcvQOPbPG5ziYsQtLOE1L/c=

init:
  - set PATH=%PYTHON_ROOT%;%PYTHON_ROOT%\Scripts;%PYTHON_ROOT%\Lib;%PATH%

install:
  - python --version
  - pip --version
  - pip install setuptools --upgrade
  - pip install wheel

before_build:
  - cd c:\projects\gameboycore-python
  - cp config/appveyor/user-config.jam C:\Libraries\boost_1_60_0
  - cd C:\Libraries\boost_1_60_0
  - bootstrap --with-python=python3.5
  - bjam --with-python python-debugging=off threading=multi variant=release link=static

build_script:
  - cd c:\projects\gameboycore-python
  - git submodule init
  - git submodule update
  - python setup.py build

deploy_script:
  - "echo [pypi] > %USERPROFILE%\\.pypirc"
  - "echo username: nnarain >> %USERPROFILE%\\.pypirc"
  - "echo password: %password% >> %USERPROFILE%\\.pypirc"
  - python setup.py sdist bdist_wheel upload
